//-----------------------------------------------------------------------
// FILE    : Stub.scala
// SUBJECT : Class that represents a SprocketRT stub.
// AUTHOR  : (C) Copyright 2013 by Peter C. Chapin <PChapin@vtc.vsc.edu>
//
// The strange name of this class is a hack to work around a build issue. This class must be compiled before its use
// or else the compiler doesn't "see" the nesT module type annotation. In that case the compiler produces error messages
// about nesT module type mismatches, etc. Ant apparently builds files in alphabetical order so by using a name here
// that starts with 'A' the issue is avoided.
//
//-----------------------------------------------------------------------
package edu.uvm.snowstorm.sensorbox

import edu.uvm.mininess.Declarations
import edu.uvm.scalaness.{ProgramComponentWrapper, NamedProgramComponent, MininessComponent, ModuleType, Parser}
import java.io.File

@ModuleType("""{}
               <;>
               { send(buffer: Array[UInt8]): Void;
                 change_neighbor(
                   new_value: PointerTo[
                              commandTAG { mote_id     : UInt8,
                                           command_name: UInt8,
                                           val         : UInt16,
                                           nonce       : UInt8 } ] ): Void }""")
class ANMStub extends MininessComponent {
 
  /////////
  // Code generated by the Scalaness compiler.
  /////////
  def instantiate = new ANMStub

  // private val abstractSyntax = Parser.reparse("./StubC.nc", List())
    
  val configuration =
    new ProgramComponentWrapper(new NamedProgramComponent(
      name            = "StubC",
      enclosingObject = this,
      typeParameters  = Set(),
      valueParameters = Set(),
      imports         = Declarations.extractImports(abstractSyntax),
      exports         = Declarations.extractExports(abstractSyntax),
      abstractSyntax  = abstractSyntax), "generated" + File.separator + "SensorBox")
  
  def getTypeMap  = Map()
  def getValueMap = Map()  
  ////////
  // END of Scalaness generated code.
  ////////

  "SensorBox/StubC.nc"
}
