#!/bin/bash

RTADMIN_CLASSPATH=$SCALANESS_HOME/lib/antlr-3.4.jar
RTADMIN_CLASSPATH=$SCALANESS_HOME/lib/scala-library.jar:$RTADMIN_CLASSPATH
RTADMIN_CLASSPATH=$SCALANESS_HOME/lib/scala-reflect.jar:$RTADMIN_CLASSPATH
RTADMIN_CLASSPATH=$SCALANESS_HOME/lib/scala-actors.jar:$RTADMIN_CLASSPATH
RTADMIN_CLASSPATH=$SCALANESS_HOME/../../scalaness/SpartanRPC/bin/SnowStorm.jar:$RTADMIN_CLASSPATH
RTADMIN_CLASSPATH=$SCALANESS_HOME/../../scalaness/SpartanRPC/lib/bcprov-jdk16-145.jar:$RTADMIN_CLASSPATH

java -cp $RTADMIN_CLASSPATH edu.uvm.snowstorm.Main $*
