//-----------------------------------------------------------------------
// FILE    : Stub.scala
// SUBJECT : Class that represents a SprocketRT stub.
// AUTHOR  : (C) Copyright 2013 by Peter C. Chapin <PChapin@vtc.vsc.edu>
//
//-----------------------------------------------------------------------
package edu.uvm.spartanrpc.harvester

import edu.uvm.mininess.Declarations
import edu.uvm.scalaness.{ProgramComponentWrapper, NamedProgramComponent, MininessComponent, ModuleType, Parser}
import java.io.File

@ModuleType("""{}
               <;>{ ;
               change_neighbor(
                 new_value: commandTAG { mote_id     : UInt8,
                                         command_name: UInt8,
                                         val         : UInt16,
                                         nonce       : UInt8 } ): Void }""")
class Stub extends MininessComponent {
 
  /////////
  // Code generated by the Scalaness compiler.
  /////////
  def instantiate = new Stub

  // private val abstractSyntax = Parser.reparse("./StubC.nc", List())
    
  val configuration =
    new ProgramComponentWrapper(new NamedProgramComponent(
      name            = "StubC",
      enclosingObject = this,
      typeParameters  = Set(),
      valueParameters = Set(),
      imports         = Declarations.extractImports(abstractSyntax),
      exports         = Declarations.extractExports(abstractSyntax),
      abstractSyntax  = abstractSyntax), "generated" + File.separator + "Harvester")
  
  def getTypeMap  = Map()
  def getValueMap = Map()  
  ////////
  // END of Scalaness generated code.
  ////////

  "Harvester/StubC.nc"
}
