//-----------------------------------------------------------------------
// FILE    : DisseminatorBC.scala
// SUBJECT : Instances of this class represent disseminator modules.
// AUTHOR  : (C) Copyright 2013 by Peter C. Chapin <PChapin@vtc.vsc.edu>
//
//-----------------------------------------------------------------------
package edu.uvm.spartanrpc

import edu.uvm.scalaness.{ProgramComponentWrapper, MininessComponent, ModuleType, NamedProgramComponent, Parser}
import edu.uvm.mininess.Declarations
import java.io.File

@ModuleType("""{}
               <;>{ ; }""")
class DisseminatorBC extends MininessComponent {
  /////////
  // Code generated by the Scalaness compiler.
  /////////
  // private val abstractSyntax = Parser.reparse("./SensorBox/DisseminatorBC.nc", List())

  val configuration =
    new ProgramComponentWrapper(new NamedProgramComponent(
      name            = "DisseminatorBC",
      enclosingObject = this,
      typeParameters  = Set(),
      valueParameters = Set(),
      imports         = Declarations.extractImports(abstractSyntax),
      exports         = Declarations.extractExports(abstractSyntax),
      abstractSyntax  = abstractSyntax), "generated" + File.separator + "DisseminatorBC")

  def getTypeMap  = Map()
  def getValueMap = Map()
  ////////
  // END of Scalaness generated code.
  ////////

  "SensorBox/DisseminatorBC.nc"
}
