//-----------------------------------------------------------------------
// FILE    : Stub.scala
// SUBJECT : Class that represents a SprocketRT stub.
// AUTHOR  : (C) Copyright 2013 by Peter C. Chapin <PChapin@vtc.vsc.edu>
//
//-----------------------------------------------------------------------
package edu.uvm.spartanrpc

import edu.uvm.mininess.Declarations
import edu.uvm.scalaness.{ProgramComponentWrapper, NamedProgramComponent, MininessComponent, ModuleType, Parser}
import java.io.File

@ModuleType("""{}
               <;>{ ; }""")
class Stub extends MininessComponent {
 
  /////////
  // Code generated by the Scalaness compiler.
  /////////
  // private val abstractSyntax = Parser.reparse("./StubC.nc", List())
    
  val configuration =
    new ProgramComponentWrapper(new NamedProgramComponent(
      name            = "StubC",
      enclosingObject = this,
      typeParameters  = Set(),
      valueParameters = Set(),
      imports         = Declarations.extractImports(abstractSyntax),
      exports         = Declarations.extractExports(abstractSyntax),
      abstractSyntax  = abstractSyntax), "generated" + File.separator + "BlinkClient")
  
  def getTypeMap  = Map()
  def getValueMap = Map()  
  ////////
  // END of Scalaness generated code.
  ////////

  "StubC.nc"
}
