#!/bin/bash

SNOWSTORM_CLASSPATH=$SCALANESS_HOME/lib/antlr-3.4.jar
SNOWSTORM_CLASSPATH=$SCALANESS_HOME/lib/scala-library.jar:$SNOWSTORM_CLASSPATH
SNOWSTORM_CLASSPATH=$SCALANESS_HOME/lib/scala-reflect.jar:$SNOWSTORM_CLASSPATH
SNOWSTORM_CLASSPATH=$SCALANESS_HOME/lib/scala-actors.jar:$SNOWSTORM_CLASSPATH
SNOWSTORM_CLASSPATH=$SCALANESS_HOME/../../scalaness/bin/scalaness.jar:$SNOWSTORM_CLASSPATH
SNOWSTORM_CLASSPATH=$SCALANESS_HOME/../../scalaness/SnowStorm/bin/SnowStorm.jar:$SNOWSTORM_CLASSPATH
SNOWSTORM_CLASSPATH=$SCALANESS_HOME/../../scalaness/SnowStorm/lib/bcprov-jdk16-145.jar:$SNOWSTORM_CLASSPATH

java -cp $SNOWSTORM_CLASSPATH edu.uvm.snowstorm.Main $*
